use_frameworks!

platform :ios, '9.0'

target 'CocoaPodsDemo_Example' do
  pod 'CocoaPodsDemo', :path => '../'

  target 'CocoaPodsDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
